### ISSUE TITLE
Issue-First go at Proof of History

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-sereum-d#6]
Automated Review Comments
Issues in src/tick.rs:
  - (2, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
